DjangoBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, include
from DjangoBlog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password_reset/', PasswordResetView.as_view(template_name='userprofile/password_reset_form.html',
                                                      email_template_name='userprofile/password_reset_email.html',),
         name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='userprofile/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='userprofile/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(template_name='userprofile/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from .views import *


app_name = 'article'

urlpatterns = [
    path('article-list/', article_list, name='article-list'),
    path('article-detail/<int:id>/', article_detail, name='article-detail'),
    path('article-create/', article_create, name='article-create'),
    path('article-delete/<int:id>/', article_delete, name='article-delete'),
    path('article-update/<int:id>/', article_update, name='article-update'),
]

article/models.py
from django.db import models
from django.utils import timezone


class ArticlePost(models.Model):
    author = models.ForeignKey("userprofile.UserProfile", on_delete=models.CASCADE)  # 文章作者，on_delete用于指定数据删除的方式
    title = models.CharField(max_length=100)  # 文章标题，models.CharField为字符串字段，用于保存较短的字符串
    body = models.TextField()  # 文章正文，TextField用于保存大量文本
    created = models.DateTimeField(default=timezone.now)  # 文章创建时间，default=timezone.now指定在创建数据时默认写入当前的时间
    updated = models.DateTimeField(auto_now=True)  # 文章更新时间，auto_now=True指定每次数据更新时自动写入当前时间

    class Meta:  # 内部类，用于定义元数据
        ordering = ('-created',)  # ordering指定模型返回的数据的排列顺序，'-created' 表明数据应该以文章创建时间倒序排列，负号标识倒序

    def __str__(self):  # 定义当调用对象的 str() 方法时的返回值内容
        return self.title

article/forms.py
from django import forms
from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost  # 指明数据模型的来源
        fields = ('title', 'body')  # 定义表单包含的字段

article/views.py
import markdown
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import ArticlePostForm
from .models import ArticlePost


def article_list(request):
    articles = ArticlePost.objects.all()  # 获取所有的数据对象
    context = {'articles': articles}  # 传递给模板的上下文
    return render(request, "article/list.html", context)  # render函数的作用是结合模板和上下文，并返回渲染后的HttpResponse对象


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    # 将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         'markdown.extensions.extra',   # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.codehilite',  # 语法高亮扩展
                                     ])
    context = {'article': article}
    return render(request, "article/detail.html", context)


@login_required(login_url='userprofile:login')
def article_create(request):
    if request.method == "GET":
        article_post_form = ArticlePostForm()
        context = {"article_post_form": article_post_form}
        return render(request, "article/create.html", context)
    else:
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = request.user
            new_article.save()
            return redirect("article:article-list")
        else:
            return HttpResponse("表单填写有误，请重新填写！")


def article_delete(request, id):
    if request.method == "GET":
        article = ArticlePost.objects.get(id=id)
        if article.author.id == request.user.id:
            article.delete()
            return redirect("article:article-list")
        else:
            return HttpResponse('你没有权限删除这篇文章！')


def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.method == "GET":
        context = {"article": article}
        return render(request, "article/update.html", context)
    else:
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            if article.author.id == request.user.id:
                article.title = request.POST['title']
                article.body = request.POST['body']
                article.save()
                return redirect("article:article-detail", id=id)
            else:
                return HttpResponse('你无权修改这篇文章！')
        else:
            return HttpResponse("表单内容有误，请重新填写！")

templates/article/create.html
{% extends "base.html" %}
{% block title %}创作{% endblock %}
{% block content %}
    <div class="container">
        <form method="post" action="." class="mt-4">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">文章标题</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>
            <div class="mb-3">
                <label for="body" class="form-label">文章正文</label>
                <textarea type="text" class="form-control" rows="12" id="body" name="body"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">发布</button>
        </form>
    </div>
{% endblock %}

templates/article/detail.html
{% extends "base.html" %}
{% block title %}文章详情{% endblock %}
{% block content %}
    <div class="container shadow">
        <div class="pt-4">
            <h1>{{ article.title }}</h1>
            <small class="text-secondary"><i class="bi bi-person"></i> 作者 {{ article.author }}</small>
            <small class="text-secondary mx-4"><i class="bi bi-clock"></i> 发表于 {{ article.created }}</small>
            {% if article.author.username == user.username%}
            <a href="#" class="text-decoration-none float-end text-danger ms-3"
               onclick="if(confirm('确定要删除这篇文章吗？')) location.href='{% url "article:article-delete" article.id %}'">删除</a>
            <a href="{% url "article:article-update" article.id %}" class="text-decoration-none float-end">修改</a>
            {% endif %}
        </div>
        <div class="mt-2 border-top py-2">
            {{ article.body|safe }}
        </div>
    </div>
    <script>
        // 将表格样式替换为bootstrap表格
        $('.container table').addClass('table table-bordered');
        $('.container thead').addClass('thead-light');
        // 为代码块添加圆角和内外边距
        $('.codehilite').addClass('rounded-3 p-3 my-3');
    </script>
{% endblock %}

templates/article/list.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mt-4">
            {% for article in articles %}
                <div class="col-4 mb-4">
                    <div class="card h-250">
                        <div class="card-header">
                            <h5>{{ article.title }}</h5>
                            <small class="text-secondary"><i class="bi bi-clock"></i> 发表于 {{ article.created }}</small>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ article.body|slice:'100' }}</p>
                            <!-- slice:'100'是Django的过滤器语法，表示取出正文的前100个字符，避免摘要太长 -->
                            <a href="{% url 'article:article-detail' article.id %}" class="btn btn-primary">阅读本文</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/article/update.html
{% extends "base.html" %}
{% block title %}文章修改{% endblock %}
{% block content %}
    <div class="container">
        <form method="post" action="." class="mt-4">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">文章标题</label>
                <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
            </div>
            <div class="mb-3">
                <label for="body" class="form-label">文章正文</label>
                <textarea type="text" class="form-control" rows="12" id="body" name="body">{{ article.body }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">提交修改</button>
        </form>
    </div>
{% endblock %}